markdown: kramdown

gems:
  - jekyll-assets

exclude:
  - api
  - bower.json
  - bower_components
  - docker
  - docker-compose.yml.dist
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile
  - node_modules
  - package.json
  - Rakefile
  - vendor

include:
  - .nojekyll
